# Generated by Django 4.2.2 on 2023-06-12 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='dep_description',
            new_name='dept_description',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='dep_name',
            new_name='dept_name',
        ),
    ]
